### ISSUE TITLE
Redesign payment page

### ISSUE THREAD

**Issue by lukebennett88** [mrhut10/futuresFineFurniture#55]
I found [this website](https://www.zanui.com.au/payment-policy) while looking for furniture and noticed the monochrome payment icons in the footer.
I noticed that they had a Payment Policy page, and thought we could take some inspiration from it.
<https://www.zanui.com.au/payment-policy>
What do you think @mrhut10?

**Comment by mrhut10** [comment]
yeah sounds good, I like that they've worded the subtitles as customer questions. i.e. "what is afterpay" ...


the other issue i want to address is supporting paypal on the website.
its easy enough to do, the reason it wasn't ever implimented is the owner doesn't have a paypal account, lol.

I'll sign him up for one, and get it implimented. Would be good if paypal supports automatically paying out to his bank account so he doesn't have to do anything within it. but i'll cross that bridge if we get paypal sales.

**Comment by lukebennett88** [comment]
I’d avoid PayPal if it’s not actively losing sales or the owner asks for it. Apparently it’s a huge pain to implement and the support sucks.

Credit card processing and Afterpay should be enough for most people.

**Comment by mrhut10** [comment]
@lukebennett88 would still like to put paypall on because should just be a extra configuration within snipcart seeing they are handling the whole shopping cart and have done the hard work for us.
and i know there would be a certain percentage of people who would prefer to use paypal over cards dirrectly.

unforchantly however website doesn't support afterpay, only offer that instore. It can be done however we would have to build our own integration following afterpays API but when i've looked at previously looks like a very big job. so not in scope.

for the moment i'll close this issue, but let me know if you did still want it open @lukebennett88 

:)
