### ISSUE TITLE
CMS - so management can create, edit products

### ISSUE THREAD

**Issue by mrhut10** [mrhut10/futuresFineFurniture#58]
So far looked at

* Netlify
* Sanity
* Strapi

each seems to have there own benifits and problems.

Netlify - feels like a strugling project, futuresFineFurniture originally used this, but it had problems, currently they have outstanding 400+ issues, and 40 pull requests, feels like a project that isn't getting the support they need and this worries me.

Strapi - looks good and opensource yay!!!, however as doesn't natively support AWS serverless will need to host a server to use, plus doesn't support embedded object types (outside of just putting JSON in a text field ) which means i can't have embedded product variants for each product, a product variant would have to be inside a separate table which again would confuse management when using.

sanity.io - looks good also its hosted, free for 3 users or below. and they support embedded objects in a document..... so far i think this is the obvious choice.

however would anyone like to way in with there experiance?

@lukebennett88 @Irev-Dev

**Comment by mrhut10** [comment]
actually another one to look at is
https://forestry.io

stores on your git like netlify, and free for 3 or less users.

but haven't read enough to know how well it works

**Comment by lukebennett88** [comment]
I have very limited experience with all of these:

Netlify CMS definitely isn't as smooth as their other products, but I have faith that it will get better.
Cloudinary and Uploadcare and Netlify Large Media integrations are nice to have, as I'm starting to see the issues of hosting all your images in a GitHub repo in some of the websites I've worked on recently.

I didn't love that Strapi required a Node server instead of being a flat-file CMS or being hosted and gave up pretty quickly when I looked into it, just seemed like too much overhead for me, but it does look really nice if you want to put the time into setting it up.

I've used Sanity.io briefly, I think Stackbit had Gatsby theme with a preconfigured CMS (which was Sanity in this case) again seemed pretty good, and probably one of the more powerful but I didn't spend much time with it.

I used Forestry quite a while ago when I was using Jekyll, and didn't love it, but I was comparing it to Siteleaf which I really liked at the time (unfortunately I think Siteleaf is only for Jekyll sites).

Another CMS I'd look into is Contentful, they have a free tier and a nice interface.

My experience with these CMSs is still super limited, so this is all mostly subjective, but I'd still be tempted to give Netlify CMS another crack, I'm pretty sure it has all features you'd need for this, and is completely free.

I'd probably say Contentful or Sanity are a close second though (especially with the sweet [Syntax.fm discount](https://www.sanity.io/syntax)).

**Comment by mrhut10** [comment]
@lukebennett88 

just had a play with Forestry was really interesting. it almost just works.
however it is saving things in a different format to what my codes expecting. for example

integers like price are being stored as strings in frontmatter
and references to categories are saving as full paths to the relivent category document, rather than just there title name.

hense it is braking my build, but interesting how close it is to just working out of the box.


I'll have a quite play with sanity next

**Comment by lukebennett88** [comment]
Siteleaf does something similar, it normalises all your markdown files. Nice that it does this automatically for you, not so nice if it breaks the site 😂

Let me know how you go, CMSs are such a pain, I still haven’t found anything I like.

Another option is to move the everything over to a headless WordPress site and create a custom post type for the products. Shouldn’t be too hard to do.

But then you’d have WordPress to deal with so ¯\_(ツ)_/¯

Are you managing inventory or anything like that at the moment?

**Comment by Irev-Dev** [comment]
@mrhut10 we build https://underground-civil.netlify.com/ with sanity.io.
I can't give you any kind of comparison, but generally we were rather happy with it. It exposing data with a graphql endpoint is really nice from a gatsby standpoint, (you can even give that endpoint to https://graphql-code-generator.com/docs/plugins/typescript and get it to define all of your types for you).
I would recommend looking at https://www.sanity.io/create (either the blog or the portfolio) easiest way to get started with sanity + gatsby deployed on netlify with all of the plumbing already set up for you.

**Comment by mrhut10** [comment]
thank you @Irev-Dev i'll play with a demo project later today to see how all works :)

thats right after i fix a double discount problem that i've just uncovered :) issue #60

**Comment by mrhut10** [comment]
thank you @Irev-Dev and @lukebennett88 
just made an implimentation of database using sanity.io

code is there if you were curious, but now i have to both
* plumb in website to get this data on build
* transfer the 240+ products into sanity.io database

I'll close this issue and open a fresh one's in regard to both of those points 

:)

thank you again guys 💯
